# -*- coding: utf-8 -*-
"""Pertemuan_PSD_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfwYmM_CH8j5NeTQquGd_mP8x7CFqNwp
"""

# 1. membuat array
import array as arr
a = arr.array('i', [1, 2, 3])
print("The new created array is : ", end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()

b = arr.array('d', [2.5, 3.2, 3.3])
print("The new created array is : ", end=" ")
for i in range(0, 3):
  print(b[i], end=" ")
print()

# 2. menambahkan elemen di array
a.insert(1, 4)
print("\nArray after insertion : ", end=" ")
for i in (a):
  print(i, end=" ")
print()

b.append(4.4)
print("Array after insertion : ", end=" ")
for i in (b):
  print(i, end=" ")
print()

# 3. mengakses elemen array
print("\nAcces element is : ", a[0])
print("Acces element is : ", a[3])

print("\nAcces elemnt is : ", b[0])
print("Acces element is : ", b[3])

# 4. menghapus elemen array
import array
arr = array.array('i', [1, 2, 3, 4, 5])
print("The new created array is : ", end=" ")
for i in range(0, 5):
  print(arr[i], end=" ")

print("\r")
print("The popped element is : ", end=" ")
print(arr.pop(2))
print("The array after popping is : ", end=" ")
for i in range(0,4):
  print(arr[i], end=" ")

print("\r")
arr.remove(1)
print("The array after removing is : ", end=" ")
for i in range(0, 3):
  print(arr[i], end=" ")

#  5. pemotongan elemen array
import array as arr
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = arr.array('i', l)
print("Initial array: ")
for i in (a):
  print(i, end=" ")
Sliced_array = a[3:8]
print("\nSlicing elements in a range 3-8: ")
print(Sliced_array)

Sliced_array = a[5:]
print("\nElements sliced from 5th "
  "element till end: ")
print(Sliced_array)

Sliced_array = a[:]
print("\nPrinting all elements using slice operation: ")
print(Sliced_array)

# 6. mengubah elemen array
import array
arr = array.array('i', [1, 2, 3, 1, 2, 5])
print("array before updation: ", end=" ")
for i in range(0, 6):
  print(arr[i], end=" ")

print("\r")
arr[2] = 6
print("Array after updation: ", end="")
for i in range(0, 6):
  print(arr[i], end="")
print()

arr[4] = 8
print("Array after updation: ", end="")
for i in range(0, 6):
  print(arr[i], end=" ")

# 7. berbagai operasi array
import array
my_array = array.array('i', [1, 2, 3, 4, 2, 5, 2])

# Menghitung elemen array
count = my_array.count(2)
print("Number of occuraences of 2:", count)

# membalik elemen array
print("original array:  ", my_array)
my_array.reverse()
print("Reverseed array: ", my_array)

# extend dalam array

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])
print("the before array extend : ", end=" ")
for i in range(0, 5):
  print(a[i], end=" ")
print()

a.extend([6, 7, 8, 9, 10])
print("\nThe array after extend : ", end=" ")
for i in range(0,10):
  print(a[i], end=" ")
print()

b = arr.array('d', [2.1, 2.2, 2.3, 2.4, 2.5, 2.6])
print("\nThe before extend arrayy is : ", end=" ")
for i in range(0,6):
  print(b[i], end=" ")
print()

b.extend([2.6, 2.7, 2.8, 2.9])
print("\nThe after extend array is : ", end=" ")
for i in range(0, 9+1):
  print(b[i], end=" ")
print()